name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew test
    - name: Upload test report
      uses: actions/upload-artifact@v1
      with:
        name: test-report
        path: /home/runner/work/CloudAtlas/CloudAtlas/build/reports/tests/test
